### ISSUE TITLE
animation issue

### ISSUE THREAD

**Issue by milesje** [vic10us/paper-search-input#3]
When you click into the search field and the it changes to a white background if the window is large enough the entire search field isn't changed to white.
![paper-search-input_documentation](https://cloud.githubusercontent.com/assets/537359/17154485/d986209e-5346-11e6-8ea5-beb107aa3db7.png)

**Comment by vic10us** [comment]
Have you tried setting the '--icon-scale-factor' css variable to a larger value?

**Comment by milesje** [comment]
with a scale factor of 100 (the default) I would assume that should scale to 100% of the window. what scale would you recommend for large window sizes.

**Comment by milesje** [comment]
OK, setting this value to a arbitrarily large number fixes my issue, but would it make more sense to make this value a percentage of the screen instead of a seemingly random number? Seeing as the size of the screen can change dynamically a percentage would make more sense or if you know of a way to set the scale factor to the size of the screen that could be helpful.

**Comment by vic10us** [comment]
The issue is that the icon is not a direct child of the input. This makes it difficult to inherit dimensions without adding JavaScript. I will look into making this better in the next update.
