### ISSUE TITLE
No clear button because Iron-icons is not dependancy in bower.json

### ISSUE THREAD

**Issue by runia1** [vic10us/paper-search-input#6]
The bower.json file needs:

"iron-icons": "^1.2.0"

otherwise the clear button is not there.

**Comment by vic10us** [comment]
Good catch! I don't know how I missed that one...

**Comment by runia1** [comment]
Yeah, overall it's a great element!  Just a few tweaks and it'll work perfectly! I'll let you close this and the other issue I filed when you get them done.

**Comment by vic10us** [comment]
This should be fixed in the latest branch. I should create a release soon.

**Comment by vic10us** [comment]
Release is now done. Hope this fixes your issues. :)
