### ISSUE TITLE
value-changed event is triggered twice

### ISSUE THREAD

**Issue by sey** [vic10us/paper-search-input#7]
This is because the `value.notify` property is set to `true` and that a `value-changed` event is manually triggered in the `_valueChanged` function.  

If you have a look here: https://www.polymer-project.org/1.0/docs/devguide/properties#notify, you will see that Polymer automatically triggers an event based on the property's name.

Polymer does not send the old value though. So if you want to keep that behaviour I would suggest to set `notify` to `false` for the `value` property.

If you'd like a pull request for this I can create one.

**Comment by vic10us** [comment]
Good catch! I have a few other changes to push related to other open issues. I'll stuff it in the next push.

Thanks a bunch!

**Comment by vic10us** [comment]
v2.0.0 is now available. Check if it helps solve your issues. :)
