### ISSUE TITLE
paper-search-input vs. iron-pages

### ISSUE THREAD

**Issue by sey** [vic10us/paper-search-input#8]
The `<paper-search-input>` component does not behave correctly when it is inside an `<iron-pages>` component. The search icon does not scale properly.

The only thing they have in common is the `IronResizableBehavior`.  

Commenting the `'iron-resize': '_onIronResize'` listener of the `<paper-search-input>` component fix the problem but of course has an impact when the component has a large width and maybe more.

I didn't had much time to investigate further.

**Comment by vic10us** [comment]
I'm sorry for taking so long to get back to you. I've been busy on other projects. I just recently started the conversion to Polymer 2 (Hybrid). Once this is done I'll see if I can squeeze in a fix if needed. :)
